CREATE DATABASE vote;
CREATE USER test2 WITH PASSWORD '123456';
GRANT CONNECT ON DATABASE vote TO test2;

\c invoice postgres
GRANT USAGE, CREATE ON SCHEMA public TO test2;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO test2;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO test2;
